import type {Appointment,CarePlan,Consultation,FollowUp,Notification,PatientProfile,PHC,ProgressEntry,Referral,Screening,UploadRecord,User} from '../types';
const KEY='drishti_ai_prod_v3';
export type DB={users:User[];patients:PatientProfile[];phcs:PHC[];appointments:Appointment[];screenings:Screening[];referrals:Referral[];notifications:Notification[];reports:UploadRecord[];carePlans:CarePlan[];progress:ProgressEntry[];consultations:Consultation[];followUps:FollowUp[]};
const initial:DB={users:[],patients:[],phcs:[],appointments:[],screenings:[],referrals:[],notifications:[],reports:[],carePlans:[],progress:[],consultations:[],followUps:[]};
export function readDB():DB{try{const x=localStorage.getItem(KEY);if(!x){localStorage.setItem(KEY,JSON.stringify(initial));return structuredClone(initial)}return {...structuredClone(initial),...JSON.parse(x)}}catch{return structuredClone(initial)}}
export function writeDB(db:DB){localStorage.setItem(KEY,JSON.stringify(db));window.dispatchEvent(new Event('drishti-db'))}
export const uid=(p='id')=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
export function registerPatient(name:string,email:string,password:string){const cleanEmail=email.trim().toLowerCase();if(!/^[a-zA-Z0-9._%+-]+@gmail\.com$/i.test(cleanEmail))throw new Error('Patient accounts require a valid @gmail.com address');if(!(password.length>=10&&/[A-Z]/.test(password)&&/[a-z]/.test(password)&&/\d/.test(password)&&/[^A-Za-z0-9]/.test(password)))throw new Error('Password must be 10+ characters with uppercase, lowercase, number and special character');const db=readDB();if(db.users.some(u=>u.email.toLowerCase()===cleanEmail))throw new Error('Email already registered');const u:User={id:uid('u'),role:'patient',name:name.trim(),email:cleanEmail,password,firstLogin:true};db.users.push(u);db.patients.push({id:uid('p'),userId:u.id,name:name.trim(),email:cleanEmail,profileComplete:20});writeDB(db);return u}
export function registerDoctor(name:string,email:string,password:string){const db=readDB();if(db.users.some(u=>u.email.toLowerCase()===email.toLowerCase()))throw new Error('Email already registered');const u:User={id:uid('u'),role:'doctor',name,email,password};db.users.push(u);writeDB(db);return u}
export function registerPHCCenter(name:string,code:string,location:string,contact:string,responsible:string,email:string,password:string,latitude?:number,longitude?:number){const db=readDB();if(db.users.some(u=>u.email.toLowerCase()===email.toLowerCase()))throw new Error('Email already registered');if(db.phcs.some(p=>p.code.toLowerCase()===code.toLowerCase()))throw new Error('PHC code already registered');const p:PHC={id:uid('phc'),name,code,location,contact,responsible,latitude,longitude,services:['Fundus screening','DR screening','Tele-ophthalmology']};const u:User={id:uid('u'),role:'phc',name:`${name} Workspace`,email,password,phcId:p.id};db.phcs.push(p);db.users.push(u);writeDB(db);return u}
export const login=(email:string,password:string)=>readDB().users.find(u=>u.email.toLowerCase()===email.toLowerCase()&&u.password===password);
export function updatePatient(userId:string,patch:Partial<PatientProfile>){const db=readDB();const i=db.patients.findIndex(p=>p.userId===userId);if(i>=0){db.patients[i]={...db.patients[i],...patch};writeDB(db);return db.patients[i]}}
export function notify(db:DB,userId:string,title:string,message:string){db.notifications.unshift({id:uid('n'),userId,title,message,createdAt:new Date().toISOString(),read:false})}
export function addAppointment(a:Appointment){const db=readDB();db.appointments.push(a);const pu=db.patients.find(p=>p.id===a.patientId)?.userId||a.patientId;notify(db,pu,'Booking confirmed',`Your retinal screening is booked for ${a.date} at ${a.slot}.`);db.users.filter(u=>u.role==='phc'&&u.phcId===a.phcId).forEach(u=>notify(db,u.id,'New appointment','A patient booked a retinal screening.'));writeDB(db)}
export function saveScreening(s:Screening){const db=readDB();const i=db.screenings.findIndex(x=>x.id===s.id);i>=0?db.screenings[i]=s:db.screenings.push(s);if(s.aiResult)db.users.filter(u=>u.role==='doctor').forEach(u=>notify(db,u.id,s.aiResult!.referable?'Priority retinal case':'New retinal case','A PHC fundus screening is ready for specialist review.'));writeDB(db)}
export function saveReferral(r:Referral){const db=readDB();const i=db.referrals.findIndex(x=>x.id===r.id);i>=0?db.referrals[i]=r:db.referrals.push(r);const pu=db.patients.find(p=>p.id===r.patientId)?.userId||r.patientId;notify(db,pu,'Referral update',`Referral status: ${r.status}.`);writeDB(db)}
export function saveCarePlan(c:CarePlan){const db=readDB();const i=db.carePlans.findIndex(x=>x.patientId===c.patientId);i>=0?db.carePlans[i]=c:db.carePlans.push(c);const pu=db.patients.find(p=>p.id===c.patientId)?.userId; if(pu)notify(db,pu,'Care plan updated','Your retina specialist updated your care plan.');writeDB(db)}
export function saveConsultation(c:Consultation){const db=readDB();const i=db.consultations.findIndex(x=>x.id===c.id);i>=0?db.consultations[i]=c:db.consultations.push(c);const pu=db.patients.find(p=>p.id===c.patientId)?.userId;if(pu)notify(db,pu,'Video consultation update',`Consultation status: ${c.status}.`);writeDB(db)}
export function markUserOnboarded(userId:string){const db=readDB();const u=db.users.find(x=>x.id===userId);if(u)u.firstLogin=false;writeDB(db)}
