import {useMemo,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {AlertCircle,Building2,Check,CheckCircle2,Eye,EyeOff,HeartPulse,LockKeyhole,Mail,Phone,ShieldCheck,Stethoscope,UserRound} from 'lucide-react';
import {Brand} from '../components/Common';
import {useAuth} from '../contexts/AuthContext';
import {updatePatient} from '../services/db';

const roles=[['Patient','Personal screening journey','/register',HeartPulse],['PHC Center','Fundus screening operations','/register-phc',Building2],['Retina Specialist','Clinical review & follow-up','/register-doctor',Stethoscope]] as const;
const gmailOk=(email:string)=>/^[a-zA-Z0-9._%+-]+@gmail\.com$/i.test(email.trim());
const passwordRules=(password:string)=>({length:password.length>=10,upper:/[A-Z]/.test(password),lower:/[a-z]/.test(password),number:/\d/.test(password),special:/[^A-Za-z0-9]/.test(password)});
const strongPassword=(password:string)=>Object.values(passwordRules(password)).every(Boolean);

export function Login(){
  const {login}=useAuth();const nav=useNavigate();const[email,setE]=useState('');const[p,setP]=useState('');const[err,setErr]=useState('');const[show,setShow]=useState(false);
  function go(){try{setErr('');const u=login(email.trim(),p);nav(`/${u.role==='phc'?'phc':u.role}/dashboard`)}catch(e:any){setErr(e.message)}}
  return <div className="auth-page premium-auth"><div className="auth-art premium-auth-art"><Brand/><div className="auth-story"><span className="eyebrow light">Connected retinal care</span><h2>One patient journey. From risk screening to retinal review.</h2><p>Build your health profile, complete guided eye capture, find a PHC when needed, and keep retinal reports and specialist follow-up connected.</p><div className="auth-proof-grid"><span><CheckCircle2 size={16}/>Guided patient screening</span><span><CheckCircle2 size={16}/>PHC fundus workflow</span><span><CheckCircle2 size={16}/>Specialist-finalized result</span></div><div className="mini-flow"><span>Patient</span><i/><span>PHC</span><i/><span>AI support</span><i/><span>Specialist</span></div></div><span>DRISHTI‑AI • Explainable screening workflow</span></div><div className="auth-form premium-auth-form"><div className="form-card wide premium-form-card"><Brand/><div className="auth-title-row"><div><span className="eyebrow">Secure workspace</span><h1>Welcome back</h1><p className="muted">Sign in to continue your DRISHTI‑AI journey.</p></div><div className="auth-shield"><ShieldCheck size={26}/></div></div>{err&&<div className="error auth-error"><AlertCircle size={16}/>{err}</div>}<div className="field icon-field"><label>Email</label><Mail size={17}/><input className="input" value={email} onChange={e=>setE(e.target.value)} placeholder="you@gmail.com" autoComplete="email"/></div><div className="field icon-field password-field"><label>Password</label><LockKeyhole size={17}/><input className="input" type={show?'text':'password'} value={p} onChange={e=>setP(e.target.value)} placeholder="Your password" autoComplete="current-password"/><button type="button" className="password-toggle" onClick={()=>setShow(x=>!x)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div><button className="btn primary auth-primary" onClick={go} disabled={!email||!p}>Secure Login</button><div className="auth-links"><Link to="/forgot">Forgot password?</Link><Link to="/demo">Watch demo</Link></div><div className="role-pick"><p className="small"><b>New to DRISHTI‑AI?</b> Create the correct workspace:</p>{roles.map(([t,d,to,I])=><Link className="role-mini" to={to} key={t}><I size={18}/><span><b>{t}</b><small>{d}</small></span></Link>)}</div></div></div></div>
}

export function Register(){
  const {register}=useAuth();const nav=useNavigate();
  const[n,setN]=useState('');const[e,setE]=useState('');const[p,setP]=useState('');const[confirm,setConfirm]=useState('');const[phone,setPhone]=useState('');const[dob,setDob]=useState('');const[gender,setGender]=useState('');const[address,setAddress]=useState('');const[emergency,setEmergency]=useState('');const[err,setErr]=useState('');const[show,setShow]=useState(false);const[consent,setConsent]=useState(false);
  const rules=useMemo(()=>passwordRules(p),[p]);const score=Object.values(rules).filter(Boolean).length;const formReady=Boolean(n.trim()&&gmailOk(e)&&phone.trim().length>=10&&dob&&gender&&address.trim()&&emergency.trim().length>=10&&strongPassword(p)&&p===confirm&&consent);
  function submit(){try{setErr('');if(!gmailOk(e))throw new Error('Patient registration accepts Gmail addresses only, for example name@gmail.com.');if(!strongPassword(p))throw new Error('Create a stronger password that meets all five security rules.');if(p!==confirm)throw new Error('Passwords do not match.');if(!formReady)throw new Error('Complete all required account fields before continuing.');const u=register(n.trim(),e.trim().toLowerCase(),p);updatePatient(u.id,{phone:phone.trim(),dob,gender,address:address.trim(),emergencyContact:emergency.trim(),profileComplete:55});nav('/patient/dashboard')}catch(x:any){setErr(x.message)}}
  return <div className="auth-page premium-auth register-premium"><div className="auth-art premium-auth-art"><Brand/><div className="auth-story"><span className="eyebrow light">Patient account setup</span><h2>Your complete screening account starts here.</h2><p>Identity, contact, health screening, eye capture, PHC booking, reports and specialist follow-up stay connected to one patient profile.</p><div className="account-journey"><span className="active"><b>01</b>Account</span><span><b>02</b>Health Q&A</span><span><b>03</b>Eye capture</span><span><b>04</b>Result & next step</span></div></div><span>DRISHTI‑AI • Patient pathway</span></div><div className="auth-form premium-auth-form"><div className="form-card wide premium-form-card register-card"><Brand/><div className="auth-title-row"><div><span className="eyebrow">Patient account</span><h1>Create your DRISHTI account</h1><p className="muted">All fields below are required. Patient signup currently accepts <b>@gmail.com</b> addresses only.</p></div><div className="auth-shield"><UserRound size={26}/></div></div>{err&&<div className="error auth-error"><AlertCircle size={16}/>{err}</div>}
    <div className="registration-section"><div className="registration-heading"><span>01</span><div><b>Personal details</b><small>Used on your booking and reports</small></div></div><div className="grid grid-2"><div className="field icon-field"><label>Full name *</label><UserRound size={17}/><input className="input" value={n} onChange={x=>setN(x.target.value)} placeholder="Your full name"/></div><div className="field icon-field"><label>Gmail address *</label><Mail size={17}/><input className={`input ${e&&!gmailOk(e)?'invalid-input':''}`} type="email" value={e} onChange={x=>setE(x.target.value)} placeholder="name@gmail.com" autoComplete="email"/>{e&&!gmailOk(e)&&<small className="field-error">Only @gmail.com is allowed for patient accounts.</small>}</div><div className="field icon-field"><label>Phone *</label><Phone size={17}/><input className="input" value={phone} onChange={x=>setPhone(x.target.value.replace(/[^0-9+]/g,''))} placeholder="10-digit mobile number" inputMode="tel"/></div><div className="field"><label>Date of birth *</label><input className="input" type="date" value={dob} onChange={x=>setDob(x.target.value)}/></div><div className="field"><label>Gender *</label><select className="select" value={gender} onChange={x=>setGender(x.target.value)}><option value="">Select</option><option>Female</option><option>Male</option><option>Other / prefer not to say</option></select></div><div className="field icon-field"><label>Emergency contact *</label><Phone size={17}/><input className="input" value={emergency} onChange={x=>setEmergency(x.target.value.replace(/[^0-9+]/g,''))} placeholder="Emergency phone number" inputMode="tel"/></div></div><div className="field"><label>Address / locality *</label><input className="input" value={address} onChange={x=>setAddress(x.target.value)} placeholder="Area, city, state"/></div></div>
    <div className="registration-section"><div className="registration-heading"><span>02</span><div><b>Account security</b><small>Use a strong unique password</small></div></div><div className="grid grid-2"><div className="field icon-field password-field"><label>Password *</label><LockKeyhole size={17}/><input className="input" type={show?'text':'password'} value={p} onChange={x=>setP(x.target.value)} placeholder="Create strong password" autoComplete="new-password"/><button type="button" className="password-toggle" onClick={()=>setShow(x=>!x)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div><div className="field icon-field"><label>Confirm password *</label><LockKeyhole size={17}/><input className={`input ${confirm&&p!==confirm?'invalid-input':''}`} type={show?'text':'password'} value={confirm} onChange={x=>setConfirm(x.target.value)} placeholder="Re-enter password" autoComplete="new-password"/></div></div><div className="password-strength"><div className="strength-track"><i style={{width:`${score*20}%`}}/></div><div className="password-rule-grid"><span className={rules.length?'ok':''}><Check size={13}/>10+ characters</span><span className={rules.upper?'ok':''}><Check size={13}/>Uppercase</span><span className={rules.lower?'ok':''}><Check size={13}/>Lowercase</span><span className={rules.number?'ok':''}><Check size={13}/>Number</span><span className={rules.special?'ok':''}><Check size={13}/>Special character</span></div></div></div>
    <label className="consent-row"><input type="checkbox" checked={consent} onChange={x=>setConsent(x.target.checked)}/><span><b>I confirm these details are mine.</b><small>I understand DRISHTI‑AI provides screening support and does not replace an ophthalmologist.</small></span></label><button disabled={!formReady} className="btn primary auth-primary" onClick={submit}>Create secure account & start health Q&A</button><p className="small auth-footnote">Already registered? <Link to="/login">Login</Link></p></div></div></div>
}

export function Forgot(){return <div className="auth-form premium-auth-form" style={{minHeight:'100vh'}}><div className="form-card premium-form-card"><Brand/><span className="eyebrow">Account recovery</span><h1>Reset password</h1><p className="muted">This prototype uses local browser authentication. In production, connect an approved authentication provider for verified email delivery and password recovery.</p><div className="field icon-field"><label>Gmail address</label><Mail size={17}/><input className="input" type="email" placeholder="name@gmail.com"/></div><button className="btn primary" onClick={()=>alert('Reset request recorded in development mode.')}>Request reset</button><div style={{marginTop:18}}><Link to="/login">Back to login</Link></div></div></div>}
