import {useState} from 'react';import {ArrowLeft,ArrowRight,BrainCircuit,CalendarDays,Camera,CheckCircle2,FileText,Stethoscope,UserRound} from 'lucide-react';import {Link} from 'react-router-dom';import {Brand,Status} from '../components/Common';
const steps=[
{title:'Demo Patient',icon:UserRound,body:<><h2>Patient onboarding</h2><p>A controlled demo profile shows how health context, previous eye history and uploaded reports enter the pathway.</p><div className="grid grid-2"><div className="card"><span className="small">Diabetes context</span><h3>Demo-only patient history</h3><p>Clearly isolated from real accounts.</p></div><div className="card"><span className="small">Reports</span><h3>Example HbA1c report</h3><p>Demo document placeholder.</p></div></div></>},
{title:'Appointment',icon:CalendarDays,body:<><h2>PHC booking</h2><div className="card"><h3>Demo PHC Center</h3><p>Screening slot: 10:30 AM • Demo date</p><Status>Confirmed</Status></div></>},
{title:'Fundus Capture',icon:Camera,body:<><h2>Right + Left eye capture</h2><p>The real product uses an external fundus-camera adapter, not the laptop webcam.</p><div className="eye-workspace"><div className="eye-preview"><div className="retina" style={{width:260,borderWidth:7}}/><div className="guide"/></div><div className="eye-preview"><div className="retina" style={{width:260,borderWidth:7}}/><div className="guide"/></div></div></>},
{title:'AI Explainability',icon:BrainCircuit,body:<><span className="eyebrow">Demo AI Screening Recommendation</span><h2>Level 2 — Moderate NPDR</h2><p><b>Demo confidence:</b> 86%</p><div className="disclaimer">Example result shown only in Watch Demo. It is not a real clinical finding or validated medical output.</div><div style={{height:260,borderRadius:20,marginTop:16,background:'radial-gradient(circle at 60% 38%, rgba(255,85,65,.7), transparent 15%), radial-gradient(circle at 34% 70%, rgba(255,192,83,.45), transparent 20%), #26383b',display:'grid',placeItems:'center',color:'white'}}><b>Demo Grad-CAM / lesion evidence visualization</b></div></>},
{title:'Doctor Review',icon:Stethoscope,body:<><h2>Ophthalmologist review</h2><div className="grid grid-2"><div className="card"><span className="small">AI recommendation</span><h3>Demo Level 2</h3></div><div className="card"><span className="small">Final clinical assessment</span><h3>Demo Level 2 — Referable</h3></div></div><p>The final decision is explicitly separated from AI screening support.</p></>},
{title:'Final Report',icon:FileText,body:<><h2>Report, referral & follow-up</h2><div className="report"><Status>Demo report</Status><h3>Connected end-to-end record</h3><p>Patient context → PHC screening → image quality → AI explanation → ophthalmologist assessment → referral/follow-up.</p><div className="notice">All content in this demo is predefined and isolated from the real application data store.</div></div></>}
];
export function Demo(){const[i,setI]=useState(0);const s=steps[i];return <div className="demo-shell"><div className="demo-banner">WATCH DEMO — predefined example data only. Nothing here is written to real user records.</div><header className="container nav"><Brand/><Link to="/" className="btn ghost"><ArrowLeft size={16}/>Exit demo</Link></header><section className="container demo-stage"><div className="demo-flow"><aside className="demo-nav">{steps.map((x,n)=><button key={x.title} className={'demo-step '+(n===i?'active':'')} onClick={()=>setI(n)}>{n+1}. {x.title}</button>)}</aside><main className="card" style={{minHeight:520,padding:30}}>{s.body}<div style={{display:'flex',justifyContent:'space-between',marginTop:30}}><button className="btn ghost" disabled={i===0} onClick={()=>setI(i-1)}><ArrowLeft size={16}/>Back</button>{i<steps.length-1?<button className="btn primary" onClick={()=>setI(i+1)}>Next step<ArrowRight size={16}/></button>:<Link to="/register" className="btn primary">Create real patient account</Link>}</div></main></div></section></div>}
