import {useEffect,useMemo,useRef,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {Activity,AlertTriangle,BadgeCheck,BrainCircuit,CalendarDays,Camera,ChevronRight,Clock3,Droplets,Eye,FileCheck2,FileDown,FileText,Image as ImageIcon,MapPin,Play,RefreshCw,Save,ShieldCheck,Stethoscope,UploadCloud,UserPlus,Video} from 'lucide-react';
import {jsPDF} from 'jspdf';
import {Empty,PageTitle,PortalLayout,Status} from '../components/Common';
import {useAuth} from '../contexts/AuthContext';
import {readDB,saveConsultation,saveReferral,saveScreening,uid,writeDB} from '../services/db';
import {runTrainedDRModel} from '../services/ai';
import type {Appointment,ClinicalFindingRow,ClinicalObservation,EyeScreening,PHCClinicalContext,PHCDetailedReport,Quality,Screening,Severity,UploadRecord} from '../types';
import {toUpload} from '../utils/files';
import {assessFundusQuality} from '../services/quality';
import {extractDiabetesReport} from '../services/reportExtraction';

const links=[
  {to:'/phc/dashboard',label:'Dashboard'},
  {to:'/phc/appointments',label:"Today's Bookings"},
  {to:'/phc/patients',label:'Patients'},
  {to:'/phc/new-patient',label:'New Patient'},
  {to:'/phc/screenings',label:'Screenings'},
  {to:'/phc/reports',label:'AI Reports',icon:'reports'},
  {to:'/phc/referrals',label:'Referrals'},
  {to:'/phc/consultations',label:'Video Consultations'},
];

const severityNames=['No DR','Mild NPDR','Moderate NPDR','Severe NPDR','Proliferative DR'];
const todayISO=()=>new Date().toISOString().slice(0,10);
const fmt=(x?:string)=>x?new Date(x).toLocaleString():'—';
function ageFromDOB(dob?:string){if(!dob)return '—';const d=new Date(dob);if(Number.isNaN(d.getTime()))return '—';const now=new Date();let a=now.getFullYear()-d.getFullYear();const m=now.getMonth()-d.getMonth();if(m<0||(m===0&&now.getDate()<d.getDate()))a--;return String(a)}

export function PHCShell({view}:{view:string}){
  const {user}=useAuth();const[,r]=useState(0);
  useEffect(()=>{const f=()=>r(x=>x+1);window.addEventListener('drishti-db',f);return()=>window.removeEventListener('drishti-db',f)},[]);
  if(!user)return null;
  const db=readDB();const phc=db.phcs.find(p=>p.id===user.phcId);
  const body:any={dashboard:<PHCDash phcId={user.phcId!}/>,appointments:<Appointments phcId={user.phcId!}/>,patients:<Patients phcId={user.phcId!}/>,new:<NewPatient phcId={user.phcId!}/>,screenings:<AllScreenings phcId={user.phcId!}/>,reports:<Reports phcId={user.phcId!}/>,referrals:<Referrals phcId={user.phcId!}/>,consultations:<PHCConsultations phcId={user.phcId!}/>}[view];
  return <PortalLayout role={phc?.name||'PHC Center'} links={links}>{body}</PortalLayout>
}

function PHCDash({phcId}:{phcId:string}){
  const d=readDB();const apps=d.appointments.filter(a=>a.phcId===phcId);const today=todayISO();const screens=d.screenings.filter(s=>s.phcId===phcId);const todayApps=apps.filter(a=>a.date===today);const submitted=screens.filter(s=>s.status==='submitted');
  const completedToday=todayApps.filter(a=>a.status==='completed').length;
  return <>
    <PageTitle title="PHC Clinical Command Center" sub="Today's retinal-screening queue, fundus quality, AI reports and specialist handoff." action={<Link className="btn primary" to="/phc/new-patient"><UserPlus size={16}/>New walk-in</Link>}/>
    <div className="phc-command-hero"><div><span className="eyebrow">Live centre workflow</span><h2>{todayApps.length?`${todayApps.length} booking${todayApps.length===1?'':'s'} today`:'Ready for today’s retinal screenings'}</h2><p>Booking → patient context → diabetes report → bilateral fundus capture → CNN quality gate → trained DR model → detailed PHC report → ophthalmologist review.</p><div className="phc-hero-pills"><span><BadgeCheck size={14}/>No manual quality override</span><span><BrainCircuit size={14}/>Trained model only</span><span><ShieldCheck size={14}/>Clinician review required</span></div></div><div className="phc-hero-score"><small>Completed today</small><strong>{completedToday}/{todayApps.length||0}</strong><span>{submitted.length} awaiting specialist review</span></div></div>
    <div className="grid grid-4 dashboard-kpis"><K t="Today's bookings" n={todayApps.length}/><K t="Registered / screening" n={todayApps.filter(a=>['registered','screening'].includes(a.status)).length}/><K t="AI reports" n={screens.filter(s=>s.phcReport).length}/><K t="Reviewed" n={screens.filter(s=>s.status==='reviewed').length}/></div>
    <div className="phc-stepper"><Step n="01" t="Booking" active/><Step n="02" t="Patient context"/><Step n="03" t="Fundus + quality"/><Step n="04" t="AI report"/><Step n="05" t="Specialist"/></div>
    <div className="grid grid-2 dashboard-lower">
      <div className="card premium-queue"><div className="section-head"><div><span className="eyebrow">Today's queue</span><h3>Booked patients</h3></div><CalendarDays size={20}/></div>{todayApps.length?todayApps.sort((a,b)=>a.slot.localeCompare(b.slot)).map(a=>{const p=d.patients.find(p=>p.id===a.patientId);return <div className="phc-queue-row" key={a.id}><div className="queue-time">{a.slot}</div><div className="queue-patient"><b>{p?.name||'Patient'}</b><span>{p?.phone||p?.email||'Contact unavailable'}</span></div><Status tone={a.status==='booked'?'warn':undefined}>{a.status}</Status><Link className="btn soft mini" to={`/phc/appointment/${a.id}`}>Open <ChevronRight size={14}/></Link></div>}):<Empty title="No bookings today" body="Online bookings and same-day walk-ins will appear here." action={<Link className="btn soft" to="/phc/new-patient">Add walk-in</Link>}/>}</div>
      <div className="card"><div className="section-head"><div><span className="eyebrow">Operations</span><h3>Clinical alerts</h3></div><Activity size={20}/></div>{d.notifications.filter(n=>d.users.some(u=>u.id===n.userId&&u.role==='phc'&&u.phcId===phcId)).slice(0,6).length?d.notifications.filter(n=>d.users.some(u=>u.id===n.userId&&u.role==='phc'&&u.phcId===phcId)).slice(0,6).map(n=><div key={n.id} className="notification-compact"><b>{n.title}</b><span>{n.message}</span></div>):<p className="muted">No operational alerts yet.</p>}</div>
    </div>
  </>
}

function Step({n,t,active}:{n:string;t:string;active?:boolean}){return <div className={active?'active':''}><b>{n}</b><span>{t}</span></div>}
function K({t,n}:{t:string;n:number}){return <div className="card"><span className="small">{t}</span><div className="kpi">{n}</div></div>}

function Appointments({phcId}:{phcId:string}){
  const nav=useNavigate();const d=readDB();const today=todayISO();const apps=d.appointments.filter(a=>a.phcId===phcId&&a.date===today).sort((a,b)=>a.slot.localeCompare(b.slot));
  return <><PageTitle title="Today's Bookings" sub={`${new Date().toLocaleDateString()} · patients scheduled for this centre`}/>{!apps.length?<Empty title="No bookings today" body="Today's online bookings and walk-ins will appear here." action={<Link className="btn primary" to="/phc/new-patient">Register walk-in</Link>}/>:<div className="card phc-table-card"><table className="table"><thead><tr><th>Time</th><th>Patient</th><th>Diabetes context</th><th>Status</th><th/></tr></thead><tbody>{apps.map(a=>{const p=d.patients.find(p=>p.id===a.patientId);return <tr key={a.id}><td><b>{a.slot}</b></td><td><b>{p?.name}</b><div className="small">{p?.phone||p?.email}</div></td><td>{p?.onboarding?.diabetesStatus||'Not recorded'}<div className="small">{p?.onboarding?.duration||'Duration not recorded'}</div></td><td><Status tone={a.status==='booked'?'warn':undefined}>{a.status}</Status></td><td><button className="btn soft" onClick={()=>nav(`/phc/appointment/${a.id}`)}>Open case</button></td></tr>})}</tbody></table></div>}</>
}

export function AppointmentDetail(){
  const {user}=useAuth();const {id}=useParams();const nav=useNavigate();const[,tick]=useState(0);const d=readDB();const foundAppointment=d.appointments.find(x=>x.id===id&&x.phcId===user?.phcId);
  if(!foundAppointment)return <PortalLayout role="PHC" links={links}><Empty title="Appointment not found" body="This appointment is unavailable in your PHC workspace."/></PortalLayout>;
  const a=foundAppointment;const p=d.patients.find(x=>x.id===a.patientId)!;const report=d.reports.find(r=>r.id===a.initialReportId);const o=p.onboarding;const attached=o?.uploadedReports||[];
  function status(s:Appointment['status']){const db=readDB();const x=db.appointments.find(y=>y.id===a.id);if(x)x.status=s;if(s==='registered'){db.users.filter(u=>u.role==='phc'&&u.phcId===a.phcId).forEach(u=>db.notifications.unshift({id:uid('n'),userId:u.id,title:'Patient ready for screening',message:`${p.name} is registered and ready for bilateral fundus capture.`,createdAt:new Date().toISOString(),read:false}))}writeDB(db);tick(v=>v+1)}
  return <PortalLayout role="PHC" links={links}>
    <PageTitle title={p.name} sub={`${a.date} • ${a.slot} • ${a.status}`} action={<Status tone={a.status==='booked'?'warn':undefined}>{a.status}</Status>}/>
    <div className="patient-clinical-banner"><div className="patient-monogram">{p.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div><div><span className="eyebrow">Patient record</span><h2>{p.name}</h2><p>{p.email||'No email'} · {p.phone||'No phone'} · Age {ageFromDOB(p.dob)} · {p.gender||'Gender not recorded'}</p></div><div className="patient-banner-facts"><span><MapPin size={14}/>{p.address||'Address not recorded'}</span><span><Activity size={14}/>Profile {p.profileComplete}% complete</span></div></div>
    <div className="grid grid-3 patient-context-grid">
      <div className="card"><span className="eyebrow">Diabetes profile</span><Info label="Status" value={o?.diabetesStatus}/><Info label="Duration" value={o?.duration}/><Info label="Treatment" value={o?.treatment}/><Info label="Medication" value={o?.medication}/><Info label="HbA1c" value={o?.hba1c}/><Info label="BP" value={o?.systolicBP}/><Info label="Cholesterol" value={o?.cholesterol}/></div>
      <div className="card"><span className="eyebrow">Eye history & symptoms</span><Info label="Previous eye exam" value={o?.previousEyeExam}/><Info label="Previous eye problem" value={o?.eyeProblems}/><Info label="Symptoms" value={o?.symptoms}/><Info label="DR history" value={o?.drHistory}/><Info label="Current treatment" value={o?.currentTreatment}/>{o?.risk&&<div className={`risk-mini ${o.risk.band}`}><b>Patient-side preliminary risk: {o.risk.band.toUpperCase()}</b><span>{o.risk.nextStep}</span></div>}</div>
      <div className="card"><span className="eyebrow">Attached information</span>{report?<a className="attachment-row" href={report.dataUrl} download={report.name}><FileText size={18}/><span><b>Initial report</b><small>{report.name}</small></span></a>:null}{attached.length?attached.map(x=><a key={x.id} className="attachment-row" href={x.dataUrl} download={x.name}><FileCheck2 size={18}/><span><b>Patient medical upload</b><small>{x.name}</small></span></a>):<p className="muted">No diabetes/medical report uploaded by the patient yet.</p>}<div className="disclaimer">Patient-entered information is context only. PHC staff should verify clinical values against source documents before they are used in the structured report.</div></div>
    </div>
    <div className="card phc-action-card"><div><span className="eyebrow">PHC arrival</span><h3>{a.status==='booked'?'Register patient before retinal screening':'Patient is ready for fundus screening'}</h3><p className="muted">The screening workspace preserves the same patient record and requires bilateral fundus images plus verified diabetes context.</p></div><div className="phc-action-buttons">{a.status==='booked'?<button className="btn primary" onClick={()=>status('registered')}><UserPlus size={16}/>Register Patient</button>:<button className="btn primary" onClick={()=>{status('screening');nav(`/phc/screen/${a.id}`)}}><Play size={16}/>Start Fundus Screening</button>}</div></div>
  </PortalLayout>
}

function Info({label,value}:{label:string;value?:string}){return <div className="clinical-info-row"><span>{label}</span><b>{value||'Not provided'}</b></div>}

function Patients({phcId}:{phcId:string}){const d=readDB();const ids=new Set(d.appointments.filter(a=>a.phcId===phcId).map(a=>a.patientId));const ps=d.patients.filter(p=>ids.has(p.id));return <><PageTitle title="Patients" sub="Patients booked or registered at this PHC."/>{!ps.length?<Empty title="No patients yet" body="Booked or registered patients will appear here."/>:<div className="grid grid-3">{ps.map(p=>{const cases=d.screenings.filter(s=>s.patientId===p.id&&s.phcId===phcId);return <div className="card patient-list-card" key={p.id}><div className="patient-monogram small-avatar">{p.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2)}</div><h3>{p.name}</h3><p className="muted">{p.phone||p.email}</p><div className="patient-list-stats"><span><b>{cases.length}</b><small>screenings</small></span><span><b>{cases.filter(s=>s.phcReport).length}</b><small>AI reports</small></span></div></div>})}</div>}</>}

function NewPatient({phcId}:{phcId:string}){const nav=useNavigate();const[name,setName]=useState('');const[email,setEmail]=useState('');const[phone,setPhone]=useState('');const[dob,setDob]=useState('');const[gender,setGender]=useState('');function create(){if(!name.trim()||!phone.trim()||!dob||!gender)return alert('Name, phone, date of birth and gender are required.');const db=readDB();const pid=uid('p');db.patients.push({id:pid,userId:`phc-managed-${pid}`,name:name.trim(),email:email.trim(),phone:phone.trim(),dob,gender,profileComplete:55});const aid=uid('appt');db.appointments.push({id:aid,patientId:pid,phcId,date:todayISO(),slot:'Walk-in',status:'registered',initialReportId:'',createdAt:new Date().toISOString()});writeDB(db);nav(`/phc/appointment/${aid}`)}return <><PageTitle title="New walk-in patient" sub="Create a PHC-managed record from verified staff-entered information."/><div className="card premium-phc-form"><div className="grid grid-2"><Field label="Full name"><input className="input" value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Phone"><input className="input" value={phone} onChange={e=>setPhone(e.target.value)}/></Field><Field label="Email (optional)"><input className="input" value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Date of birth"><input className="input" type="date" value={dob} onChange={e=>setDob(e.target.value)}/></Field><Field label="Gender"><select className="select" value={gender} onChange={e=>setGender(e.target.value)}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option><option>Prefer not to say</option></select></Field></div><button className="btn primary" onClick={create}>Create patient & open case</button></div></>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}

function defaultClinicalContext(p:any):PHCClinicalContext{
  const o=p?.onboarding;const attached=(o?.uploadedReports||[]) as UploadRecord[];
  return {diabetesReport:attached[attached.length-1],hba1c:o?.hba1c||'',fastingGlucose:'',postMealGlucose:'',randomGlucose:'',systolicBP:o?.systolicBP||'',diastolicBP:'',cholesterol:o?.cholesterol||'',creatinine:'',diabetesDuration:o?.duration||'',diabetesTreatment:o?.treatment||'',currentMedicines:o?.medication||'',source:attached.length?'mixed':'patient-history',verifiedByPHC:false,notes:''};
}
function emptyObs():ClinicalObservation{return {visualAcuity:'',intraocularPressure:'',anteriorSegment:'',ophthalmoscopy:'',retinalStructure:'',opticDisc:'',macula:'',vessels:'',microaneurysm:'',hemorrhage:'',exudate:'',cottonWoolSpots:'',neovascularization:'',laserScars:'',retinalEdema:'',oct:'',fluoresceinAngiography:'',visualField:'',other:'',notes:''}}
function mkEye(eye:'right'|'left'):EyeScreening{return {eye,quality:'good',observations:emptyObs()}}

function obsValue(v?:string){return v?.trim()||'Not performed / not entered'}
function buildClinicalFindingRows(s:Screening):ClinicalFindingRow[]{
  const r=s.right.observations,l=s.left.observations,ai=s.aiResult;
  const aiR=ai?.perEye?.right?.label||'AI result unavailable',aiL=ai?.perEye?.left?.label||'AI result unavailable';
  const rows:ClinicalFindingRow[]=[
    {examination:'Best-corrected / available visual acuity (BCVA)',right:obsValue(r.visualAcuity),left:obsValue(l.visualAcuity),source:(r.visualAcuity||l.visualAcuity)?'PHC entered':'Not performed'},
    {examination:'Intraocular pressure (IOP)',right:obsValue(r.intraocularPressure),left:obsValue(l.intraocularPressure),source:(r.intraocularPressure||l.intraocularPressure)?'PHC entered':'Not performed'},
    {examination:'Anterior segment examination',right:obsValue(r.anteriorSegment),left:obsValue(l.anteriorSegment),source:(r.anteriorSegment||l.anteriorSegment)?'PHC entered':'Not performed'},
    {examination:'Color fundus photograph / AI DR grade',right:`${aiR}; fundus quality ${s.right.quality} ${s.right.qualityScore??'—'}/100`,left:`${aiL}; fundus quality ${s.left.quality} ${s.left.qualityScore??'—'}/100`,source:'AI + PHC'},
    {examination:'Ophthalmoscopy / retinal appearance',right:obsValue(r.ophthalmoscopy||r.retinalStructure),left:obsValue(l.ophthalmoscopy||l.retinalStructure),source:(r.ophthalmoscopy||r.retinalStructure||l.ophthalmoscopy||l.retinalStructure)?'PHC entered':'Not performed'},
    {examination:'Optic disc',right:obsValue(r.opticDisc),left:obsValue(l.opticDisc),source:(r.opticDisc||l.opticDisc)?'PHC entered':'Not performed'},
    {examination:'Macula / foveal region',right:obsValue(r.macula),left:obsValue(l.macula),source:(r.macula||l.macula)?'PHC entered':'Not performed'},
    {examination:'Retinal vessels',right:obsValue(r.vessels),left:obsValue(l.vessels),source:(r.vessels||l.vessels)?'PHC entered':'Not performed'},
    {examination:'Microaneurysms',right:obsValue(r.microaneurysm),left:obsValue(l.microaneurysm),source:(r.microaneurysm||l.microaneurysm)?'PHC entered':'Not performed'},
    {examination:'Retinal hemorrhages',right:obsValue(r.hemorrhage),left:obsValue(l.hemorrhage),source:(r.hemorrhage||l.hemorrhage)?'PHC entered':'Not performed'},
    {examination:'Hard exudates',right:obsValue(r.exudate),left:obsValue(l.exudate),source:(r.exudate||l.exudate)?'PHC entered':'Not performed'},
    {examination:'Cotton-wool spots',right:obsValue(r.cottonWoolSpots),left:obsValue(l.cottonWoolSpots),source:(r.cottonWoolSpots||l.cottonWoolSpots)?'PHC entered':'Not performed'},
    {examination:'Neovascularization',right:obsValue(r.neovascularization),left:obsValue(l.neovascularization),source:(r.neovascularization||l.neovascularization)?'PHC entered':'Not performed'},
    {examination:'Laser scars / prior retinal treatment',right:obsValue(r.laserScars),left:obsValue(l.laserScars),source:(r.laserScars||l.laserScars)?'PHC entered':'Not performed'},
    {examination:'Retinal edema / thickening',right:obsValue(r.retinalEdema),left:obsValue(l.retinalEdema),source:(r.retinalEdema||l.retinalEdema)?'PHC entered':'Not performed'},
    {examination:'SD-OCT',right:obsValue(r.oct),left:obsValue(l.oct),source:(r.oct||l.oct)?'PHC entered':'Not performed'},
    {examination:'Fluorescein angiography / UWFA',right:obsValue(r.fluoresceinAngiography),left:obsValue(l.fluoresceinAngiography),source:(r.fluoresceinAngiography||l.fluoresceinAngiography)?'PHC entered':'Not performed'},
    {examination:'Visual field',right:obsValue(r.visualField),left:obsValue(l.visualField),source:(r.visualField||l.visualField)?'PHC entered':'Not performed'},
    {examination:'Other clinical finding',right:obsValue(r.other),left:obsValue(l.other),source:(r.other||l.other)?'PHC entered':'Not performed'},
  ];
  return rows;
}

function buildDetailedReport(s:Screening,p:any):PHCDetailedReport{
  if(!s.aiResult)throw new Error('AI result is required before report generation.');
  const ai=s.aiResult;const c=s.clinicalContext!;const sev=ai.severity;const right=ai.perEye?.right;const left=ai.perEye?.left;
  const systemic:string[]=[];
  if(c.reportAnalysis){systemic.push(`Diabetes report auto-analysis: ${c.reportAnalysis.method} · extraction confidence ${c.reportAnalysis.overallConfidence}%${c.verifiedByPHC?' · PHC verified':' · awaiting/without PHC verification'}.`)}
  if(c.diabetesDuration)systemic.push(`Diabetes duration recorded: ${c.diabetesDuration}. Duration is a known retinopathy-risk context.`);
  if(c.hba1c)systemic.push(`HbA1c recorded: ${c.hba1c}. Glycemic control is relevant to retinopathy onset/progression; individual treatment targets vary.`);
  if(c.systolicBP||c.diastolicBP)systemic.push(`Blood pressure recorded: ${c.systolicBP||'—'}/${c.diastolicBP||'—'} mmHg. Blood-pressure control is relevant to retinopathy progression.`);
  if(c.cholesterol)systemic.push(`Lipid/cholesterol context recorded: ${c.cholesterol}. Dyslipidemia is a relevant systemic risk context.`);
  if(c.creatinine)systemic.push(`Creatinine/renal context recorded: ${c.creatinine}. Kidney disease can be associated with higher diabetic-retinopathy risk.`);
  if(p?.onboarding?.risk?.reasons?.length)systemic.push(...p.onboarding.risk.reasons.slice(0,4).map((x:string)=>`Patient history: ${x}`));
  const retinal=[...(ai.findings||[])];
  if(right)retinal.unshift(`Right eye: ${right.label} · model confidence ${Math.round(right.confidence*100)}%.`);
  if(left)retinal.unshift(`Left eye: ${left.label} · model confidence ${Math.round(left.confidence*100)}%.`);
  let recommendation='No urgent retina referral is generated from the AI result alone. Clinician review remains required.';let followUp='Continue routine diabetes eye-screening follow-up according to the patient’s clinician and prior examination history.';let priority:PHCDetailedReport['priority']='routine';
  if(sev===1){recommendation='Mild NPDR signal from the research model. Ophthalmologist review is still required before the result is treated as a clinical diagnosis.';followUp='At least routine/annual retinal follow-up is commonly used when retinopathy is present; the reviewing clinician should set the exact interval.'}
  if(sev===2){recommendation='Referable screening result (moderate NPDR signal). Coordinate ophthalmology/retina review.';followUp='Prompt specialist review is recommended; exact timing should be determined by the reviewing clinician.';priority='priority'}
  if(sev===3){recommendation='High-priority referable screening result (severe NPDR signal). Escalate for retina/ophthalmology review.';followUp='Priority specialist assessment is recommended; the ophthalmologist determines urgency and follow-up.';priority='urgent'}
  if(sev===4){recommendation='High-priority referable screening result (proliferative DR signal). Escalate promptly for retina/ophthalmology review.';followUp='Urgent specialist assessment is recommended; the ophthalmologist determines definitive diagnosis and treatment.';priority='urgent'}
  return {id:uid('phcrpt'),generatedAt:new Date().toISOString(),overallSeverity:sev,overallLabel:severityNames[sev],referable:ai.referable,confidence:ai.confidence,rightLabel:right?.label||'Not available',leftLabel:left?.label||'Not available',qualitySummary:`Right: ${s.right.quality} (${s.right.qualityScore??'—'}/100) · Left: ${s.left.quality} (${s.left.qualityScore??'—'}/100)`,systemicContext:systemic,retinalSummary:retinal,clinicalFindings:buildClinicalFindingRows(s),recommendation,followUp,priority,limitation:`This report combines a trained research fundus classifier with ${c.reportAnalysis?'automatically extracted diabetes-report data':'structured diabetes context'}${c.verifiedByPHC?' reviewed by PHC staff':' that has not been marked PHC-verified'} and staff-entered eye-test findings. OCR/PDF extraction can be wrong and does not alter the retinal model grade. Model confidence is not accuracy. Tests not actually performed are shown as not performed/not entered rather than invented. Final diagnosis and management require a qualified eye-care professional.`};
}

export function ScreeningWorkspace(){
  const {user}=useAuth();const {appointmentId}=useParams();const d=readDB();const foundAp=d.appointments.find(a=>a.id===appointmentId&&a.phcId===user?.phcId);
  if(!foundAp)return <PortalLayout role="PHC" links={links}><Empty title="Screening unavailable" body="Appointment not found."/></PortalLayout>;
  const ap=foundAp;const patient=d.patients.find(p=>p.id===ap.patientId)!;const existing=d.screenings.find(s=>s.appointmentId===ap.id);
  const[s,setS]=useState<Screening>(existing||{id:uid('screen'),appointmentId:ap.id,patientId:ap.patientId,phcId:ap.phcId,createdAt:new Date().toISOString(),right:mkEye('right'),left:mkEye('left'),clinicalContext:defaultClinicalContext(patient),status:'draft'});
  const[runningAI,setRunningAI]=useState(false);const[stage,setStage]=useState('');const autoExtractStarted=useRef(false);
  const c=s.clinicalContext||defaultClinicalContext(patient);
  const analysisReady=Boolean(c.reportAnalysis&&c.reportAnalysis.status!=='processing'&&c.reportAnalysis.status!=='failed');
  const manualContext=Boolean(c.hba1c||c.fastingGlucose||c.postMealGlucose||c.randomGlucose||c.systolicBP||c.diastolicBP||c.cholesterol||c.creatinine||c.diabetesDuration||c.diabetesTreatment||c.currentMedicines);
  const ready=Boolean(s.right.image&&s.left.image&&c.diabetesReport&&(analysisReady||manualContext)&&s.right.quality!=='unusable'&&s.left.quality!=='unusable');

  function mergeExtraction(analysis:any,rec?:UploadRecord){
    setS(prev=>{const base=prev.clinicalContext||defaultClinicalContext(patient);const patch:any={};Object.entries(analysis.fields||{}).forEach(([k,v]:any)=>{if(v?.value)patch[k]=v.value});return {...prev,clinicalContext:{...base,...patch,...(rec?{diabetesReport:rec}:{}),reportAnalysis:analysis,source:Object.keys(patch).length?'auto-extracted':base.source,verifiedByPHC:false}}})
  }
  async function analyzeReportFile(f:File,rec?:UploadRecord){setStage('Reading diabetes report and extracting clinical values…');setS(prev=>({...prev,clinicalContext:{...(prev.clinicalContext||defaultClinicalContext(patient)),...(rec?{diabetesReport:rec}:{}),reportAnalysis:{status:'processing',method:'none',overallConfidence:0,fields:{},warnings:[]}}}));const analysis=await extractDiabetesReport(f);mergeExtraction(analysis,rec);setStage(analysis.status==='failed'?'Automatic report extraction failed — review values manually.':`Diabetes report analyzed · ${Object.keys(analysis.fields||{}).length} structured value(s) captured.`);return analysis}
  async function fundusFile(eye:'right'|'left',f?:File){if(!f)return;try{const rec={...(await toUpload(f,'fundus')),source:'fundus-camera' as const,patientId:patient.id};setStage(`Analyzing ${eye} fundus quality and gradability…`);const qa=await assessFundusQuality(rec);setS(prev=>({...prev,[eye]:{...prev[eye],image:rec,quality:qa.quality,qualityScore:qa.score,qualityGuidance:qa.guidance,qualityMethod:qa.decisionSource||'trained-cnn',enhancementApplied:qa.enhancementRecommended}}));setStage(`${eye==='right'?'Right':'Left'} fundus quality analysis complete.`)}catch(e:any){setStage('');alert(e?.message||'Unable to assess fundus image quality.')}}
  async function diabetesReport(f?:File){if(!f)return;try{const rec={...(await toUpload(f,'report')),source:'patient' as const,patientId:patient.id};await analyzeReportFile(f,rec)}catch(e:any){setStage('');alert(e?.message||'Unable to import/analyze diabetes report.')}}
  useEffect(()=>{if(autoExtractStarted.current||!c.diabetesReport?.dataUrl||c.reportAnalysis)return;autoExtractStarted.current=true;(async()=>{try{const blob=await (await fetch(c.diabetesReport!.dataUrl!)).blob();const f=new File([blob],c.diabetesReport!.name,{type:c.diabetesReport!.type||blob.type});await analyzeReportFile(f,c.diabetesReport)}catch{setStage('Existing diabetes report could not be auto-read. Replace it or enter values manually.')}})()},[c.diabetesReport?.id]);
  function setEye(eye:'right'|'left',patch:Partial<EyeScreening>){setS(prev=>({...prev,[eye]:{...prev[eye],...patch}}))}
  function setContext<K extends keyof PHCClinicalContext>(key:K,value:PHCClinicalContext[K]){setS(prev=>({...prev,clinicalContext:{...(prev.clinicalContext||defaultClinicalContext(patient)),[key]:value}}))}
  function saveDraft(){saveScreening({...s,status:'draft'});alert('PHC screening draft saved.')}
  async function runAI(){
    if(!s.right.image||!s.left.image)return alert('Upload both right and left fundus images.');
    if(s.right.quality==='unusable'||s.left.quality==='unusable')return alert('Image Ungradable — Recapture Required. AI analysis is blocked.');
    if(!c.diabetesReport)return alert('Upload the current diabetes/medical report before generating the detailed PHC report.');
    if(c.reportAnalysis?.status==='processing')return alert('Diabetes report analysis is still running.');
    if(!analysisReady&&!manualContext)return alert('The report did not yield structured values automatically. Enter/confirm the available diabetes values before generating the report.');
    try{
      setRunningAI(true);setStage('1/5 · Validating extracted diabetes-report inputs…');await new Promise(r=>setTimeout(r,350));
      setStage('2/5 · Re-checking bilateral fundus gradability…');await new Promise(r=>setTimeout(r,300));
      setStage('3/5 · Running trained per-eye diabetic-retinopathy model…');
      const base={...s,clinicalContext:c,status:'draft' as const};const ai=await runTrainedDRModel(base);
      setStage('4/5 · Fusing retinal output with systemic diabetes context…');const withAI={...base,aiResult:ai};await new Promise(r=>setTimeout(r,500));
      setStage('5/5 · Generating detailed explainable clinical report…');await new Promise(r=>setTimeout(r,500));
      const report=buildDetailedReport(withAI,patient);const next={...withAI,phcReport:report,status:'submitted' as const};
      saveScreening(next);const db=readDB();const a=db.appointments.find(x=>x.id===ap.id);if(a)a.status='completed';writeDB(db);setS(next);setStage('Detailed AI report generated and submitted for ophthalmologist review.');
    }catch(e:any){setStage('');alert(e?.message||'Trained DR model analysis failed. Make sure the AI service is connected.')}finally{setRunningAI(false)}
  }
  return <PortalLayout role="PHC" links={links}>
    <PageTitle title="Automated PHC Case Analysis" sub={`${patient.name} · diabetes report extraction + bilateral fundus AI + detailed clinical report`}/>
    <div className="clinical-readiness-strip"><div><span>01</span><b>Patient</b><small>{patient.name}</small></div><div className={analysisReady?'done':''}><span>02</span><b>Report extraction</b><small>{c.reportAnalysis?.status==='processing'?'Analyzing…':analysisReady?`${Object.keys(c.reportAnalysis?.fields||{}).length} values captured`:c.diabetesReport?'Needs review':'Upload required'}</small></div><div className={s.right.image&&s.left.image?'done':''}><span>03</span><b>Fundus analysis</b><small>{s.right.image&&s.left.image?'Both eyes loaded':'Right + Left required'}</small></div><div className={ready?'done':''}><span>04</span><b>AI report</b><small>{ready?'Ready to generate':'Complete inputs'}</small></div></div>

    <section className="card phc-context-card">
      <div className="section-head"><div><span className="eyebrow">Automatic report intelligence</span><h3>Diabetes report → structured clinical inputs</h3><p className="muted">PDF text is parsed directly; scanned PDFs/images use OCR fallback. Extracted values are auto-filled below with confidence and remain editable for PHC review.</p></div><Droplets size={24}/></div>
      <div className="diabetes-upload-zone"><UploadCloud size={24}/><div><b>{c.diabetesReport?'Diabetes report attached':'Upload diabetes report'}</b><span>{c.diabetesReport?.name||'PDF or image · preserved for ophthalmologist review'}</span></div><label className="btn soft"><input hidden type="file" accept="application/pdf,image/*" onChange={e=>diabetesReport(e.target.files?.[0])}/>{c.diabetesReport?'Replace report':'Choose report'}</label></div>
      {c.reportAnalysis&&<div className={`auto-extraction-panel ${c.reportAnalysis.status}`}><div className="auto-extraction-head"><div><span className="eyebrow">Auto-captured inputs</span><h4>{c.reportAnalysis.status==='processing'?'Reading report…':c.reportAnalysis.status==='failed'?'Automatic extraction needs review':`${Object.keys(c.reportAnalysis.fields||{}).length} clinical value(s) captured`}</h4><p>{c.reportAnalysis.method==='pdf-text'?'Native PDF text extraction':c.reportAnalysis.method==='ocr'?'English OCR from scanned report/image':c.reportAnalysis.method==='hybrid'?'PDF text + OCR fallback':'No extraction method available'} · confidence {c.reportAnalysis.overallConfidence||0}%</p></div><div className="extraction-confidence"><strong>{c.reportAnalysis.overallConfidence||0}</strong><small>/100 extraction</small></div></div>{Object.keys(c.reportAnalysis.fields||{}).length>0&&<div className="extracted-chip-grid">{Object.entries(c.reportAnalysis.fields||{}).map(([key,v]:any)=><div className="extracted-chip" key={key}><span>{key.replace(/([A-Z])/g,' $1')}</span><b>{v.value}</b><small>{v.confidence}% · auto-extracted</small></div>)}</div>}{c.reportAnalysis.warnings?.length>0&&<div className="extraction-warnings">{c.reportAnalysis.warnings.map((w,i)=><span key={i}><AlertTriangle size={13}/>{w}</span>)}</div>}</div>}
      <div className="grid grid-4 clinical-value-grid">
        <ClinicalInput label="HbA1c (%)" value={c.hba1c} onChange={v=>setContext('hba1c',v)}/><ClinicalInput label="Fasting glucose" value={c.fastingGlucose} onChange={v=>setContext('fastingGlucose',v)}/><ClinicalInput label="Post-meal glucose" value={c.postMealGlucose} onChange={v=>setContext('postMealGlucose',v)}/><ClinicalInput label="Random glucose" value={c.randomGlucose} onChange={v=>setContext('randomGlucose',v)}/><ClinicalInput label="Systolic BP" value={c.systolicBP} onChange={v=>setContext('systolicBP',v)}/><ClinicalInput label="Diastolic BP" value={c.diastolicBP} onChange={v=>setContext('diastolicBP',v)}/><ClinicalInput label="Cholesterol / lipids" value={c.cholesterol} onChange={v=>setContext('cholesterol',v)}/><ClinicalInput label="Creatinine / renal" value={c.creatinine} onChange={v=>setContext('creatinine',v)}/><ClinicalInput label="Diabetes duration" value={c.diabetesDuration} onChange={v=>setContext('diabetesDuration',v)}/><ClinicalInput label="Treatment type" value={c.diabetesTreatment} onChange={v=>setContext('diabetesTreatment',v)}/><ClinicalInput label="Current medicines" value={c.currentMedicines} onChange={v=>setContext('currentMedicines',v)}/><ClinicalInput label="PHC notes" value={c.notes} onChange={v=>setContext('notes',v)}/>
      </div>
      <label className={`verification-check ${c.verifiedByPHC?'checked':''}`}><input type="checkbox" checked={c.verifiedByPHC} onChange={e=>setContext('verifiedByPHC',e.target.checked)}/><ShieldCheck size={18}/><span><b>I reviewed the auto-extracted values against the source report</b><small>Recommended before clinical use. OCR/PDF extraction is automated but can misread values; retinal DR severity is still determined separately from the fundus model.</small></span></label>
    </section>

    <div className="eye-workspace phc-eye-workspace"><EyePanel label="Right Eye" eye={s.right} onFile={f=>fundusFile('right',f)} onChange={p=>setEye('right',p)}/><EyePanel label="Left Eye" eye={s.left} onFile={f=>fundusFile('left',f)} onChange={p=>setEye('left',p)}/></div>

    <div className="card ai-run-console"><div><span className="eyebrow">Clinical AI pipeline</span><h3>Analyze both uploads & generate the detailed AI report</h3><p className="muted">The system uses extracted diabetes-report values for systemic context and the bilateral fundus model for retinal severity. These streams are fused in the report but the lab values never fabricate or overwrite a retinal grade.</p></div><div className="ai-readiness"><span className={ready?'ready':''}>{ready?'Ready to analyze':'Inputs incomplete'}</span><button className="btn ghost" onClick={saveDraft}><Save size={16}/>Save draft</button><button className="btn primary" disabled={runningAI||!ready} onClick={runAI}><BrainCircuit size={16}/>{runningAI?'Analyzing both sources…':'Analyze uploads & generate report'}</button></div>{stage&&<div className={`ai-stage ${runningAI?'running':'done'}`}><RefreshCw size={17}/><span>{stage}</span></div>}<div className="disclaimer">No “100% accuracy” claim is made. The research model can be wrong even with high confidence. Ungradable images are blocked, confidence is shown, and ophthalmologist review remains the final clinical layer.</div></div>

    {s.aiResult&&s.phcReport&&<DetailedReportView screening={s} patient={patient}/>} 
  </PortalLayout>
}

function ClinicalInput({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div className="field compact-field"><label>{label}</label><input className="input" value={value} onChange={e=>onChange(e.target.value)} placeholder="Enter verified value"/></div>}

function EyePanel({label,eye,onFile,onChange}:{label:string;eye:EyeScreening;onFile:(f?:File)=>void;onChange:(p:Partial<EyeScreening>)=>void}){
  const o=eye.observations;const set=(k:keyof ClinicalObservation,v:string)=>onChange({observations:{...o,[k]:v}});
  return <div className="card premium-fundus-card"><div className="section-head"><div><span className="eyebrow">{label}</span><h3>Fundus image & quality gate</h3></div>{eye.image&&<Status tone={eye.quality==='unusable'?'bad':eye.quality==='enhance'?'warn':undefined}>{eye.quality}</Status>}</div>
    <div className="fundus-preview">{eye.image?.dataUrl?<img src={eye.image.dataUrl}/>:<div className="fundus-placeholder"><Eye size={34}/><b>Import color fundus image</b><span>Use fundus-camera export · not laptop webcam</span></div>}</div>
    <label className="fundus-upload-btn"><input hidden type="file" accept="image/*" onChange={e=>onFile(e.target.files?.[0])}/><Camera size={17}/>{eye.image?'Replace fundus image':'Upload fundus image'}</label>
    {eye.image?<div className={`quality-panel ${eye.quality}`}><div><b>{eye.quality==='good'?'Gradable — ready for model':eye.quality==='enhance'?'Gradable but borderline — enhancement/review':'Ungradable — recapture required'}</b><span>{eye.qualityGuidance||'Quality assessment completed.'}</span></div><div className="quality-score"><strong>{eye.qualityScore??'—'}</strong><small>/100 quality</small></div><div className="quality-source">{eye.qualityMethod==='browser-precheck'?'Browser pre-check only':eye.qualityMethod?.includes('trained')?'CNN gradability gate':'Quality service'}</div></div>:<div className="notice">A real fundus image is required. The operator cannot manually force image quality to “Good”.</div>}
    <details className="clinical-observations" open><summary>Detailed ophthalmology / retinal findings</summary><p className="small clinical-note">Enter only measurements/findings actually available at the PHC or from a connected ophthalmic device. Leave unavailable tests blank; the report will mark them as not performed.</p><div className="clinical-observation-grid">{([
      ['visualAcuity','Visual acuity / BCVA'],['intraocularPressure','Intraocular pressure (mmHg)'],['anteriorSegment','Anterior segment'],['ophthalmoscopy','Ophthalmoscopy / retinal appearance'],['retinalStructure','Retinal structure'],['opticDisc','Optic disc'],['macula','Macula / fovea'],['vessels','Retinal vessels'],['microaneurysm','Microaneurysms'],['hemorrhage','Hemorrhages'],['exudate','Hard exudates'],['cottonWoolSpots','Cotton-wool spots'],['neovascularization','Neovascularization'],['laserScars','Laser scars / prior treatment'],['retinalEdema','Retinal edema / thickening'],['oct','SD-OCT'],['fluoresceinAngiography','Fluorescein angiography / UWFA'],['visualField','Visual field'],['other','Other finding'],['notes','Clinical notes']
    ] as [keyof ClinicalObservation,string][]).map(([k,label])=><div className="field" key={String(k)}><label>{label}</label>{k==='notes'||k==='ophthalmoscopy'||k==='oct'||k==='fluoresceinAngiography'?<textarea className="textarea compact-clinical-textarea" value={o[k]||''} onChange={e=>set(k,e.target.value)} placeholder="Enter finding only if performed / observed"/>:<input className="input" value={o[k]||''} onChange={e=>set(k,e.target.value)} placeholder="Enter finding only if available"/>}</div>)}</div></details>
  </div>
}

function DetailedReportView({screening:s,patient:p}:{screening:Screening;patient:any}){
  const ai=s.aiResult!;const r=s.phcReport!;const tone=r.priority==='urgent'?'bad':r.priority==='priority'?'warn':undefined;
  return <section className="phc-report-shell"><div className="phc-report-head"><div><span className="eyebrow">Generated PHC screening report</span><h2>{r.overallLabel} · Level {r.overallSeverity}</h2><p>{p.name} · {fmt(r.generatedAt)}</p></div><div className="report-actions"><Status tone={tone}>{r.priority.toUpperCase()}</Status><button className="btn ghost" onClick={()=>downloadPHCReport(s,p)}><FileDown size={16}/>Download PDF</button></div></div>
    <div className="report-metric-grid"><ReportMetric label="Model confidence" value={`${Math.round(r.confidence*100)}%`} note="Not the same as accuracy"/><ReportMetric label="Referable" value={r.referable?'YES':'NO'} note="Prototype threshold: level 2–4"/><ReportMetric label="Right eye" value={r.rightLabel} note={`${s.right.qualityScore??'—'}/100 image quality`}/><ReportMetric label="Left eye" value={r.leftLabel} note={`${s.left.qualityScore??'—'}/100 image quality`}/></div>
    <div className="clinical-findings-card"><div className="section-head"><div><span className="eyebrow">Ophthalmology / retinal clinical findings</span><h3>Detailed examination table</h3><p className="muted">AI-derived fundus grade is kept separate from PHC-entered examination findings. Missing tests are explicitly marked.</p></div><FileText size={22}/></div><div className="clinical-findings-table-wrap"><table className="clinical-findings-table"><thead><tr><th>Examination / Test</th><th>Right eye</th><th>Left eye</th><th>Source</th></tr></thead><tbody>{(r.clinicalFindings||buildClinicalFindingRows(s)).map((row,i)=><tr key={i}><td><b>{row.examination}</b></td><td>{row.right}</td><td>{row.left}</td><td><span className={`finding-source ${row.source==='Not performed'?'muted-source':''}`}>{row.source}</span></td></tr>)}</tbody></table></div></div>
    <div className="grid grid-2 report-detail-grid"><div className="card"><span className="eyebrow">Retinal AI summary</span>{r.retinalSummary.map((x,i)=><div className="report-bullet" key={i}><BrainCircuit size={15}/><span>{x}</span></div>)}<h3 style={{marginTop:18}}>Image quality</h3><p>{r.qualitySummary}</p><p className="small">Model: {ai.model?.name||'Trained DR model'} · {ai.model?.source||'configured model source'}</p></div><div className="card"><span className="eyebrow">Systemic diabetes context</span>{r.systemicContext.length?r.systemicContext.map((x,i)=><div className="report-bullet" key={i}><Droplets size={15}/><span>{x}</span></div>):<p className="muted">No structured systemic context was available beyond the attached report.</p>}<div className="context-source"><FileCheck2 size={18}/><span><b>Source document</b><small>{s.clinicalContext?.diabetesReport?.name||'Not attached'}{s.clinicalContext?.reportAnalysis?` · ${s.clinicalContext.reportAnalysis.method} · ${s.clinicalContext.reportAnalysis.overallConfidence}% extraction confidence`:''}</small></span></div></div></div>
    <div className={`clinical-recommendation ${r.priority}`}><div><Stethoscope size={26}/><span><small>PHC coordination recommendation</small><b>{r.recommendation}</b><p>{r.followUp}</p></span></div></div>
    <div className="report-limit"><AlertTriangle size={17}/><p>{r.limitation}</p></div>
  </section>
}
function ReportMetric({label,value,note}:{label:string;value:string;note:string}){return <div className="report-metric"><span>{label}</span><b>{value}</b><small>{note}</small></div>}

function downloadPHCReport(s:Screening,p:any){
  if(!s.aiResult||!s.phcReport)return;
  const doc=new jsPDF();const r=s.phcReport;const ai=s.aiResult;let y=18;
  const page=()=>{doc.addPage();y=18};
  const ensure=(h=10)=>{if(y+h>280)page()};
  const line=(label:string,value:string)=>{ensure(12);doc.setFont('helvetica','bold');doc.text(label,16,y);doc.setFont('helvetica','normal');const lines=doc.splitTextToSize(value||'—',128);doc.text(lines,68,y);y+=Math.max(7,lines.length*5)};
  const heading=(t:string)=>{ensure(14);y+=3;doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text(t,16,y);doc.setFontSize(9);y+=7};
  doc.setFontSize(18);doc.setFont('helvetica','bold');doc.text('DRISHTI-AI — Detailed PHC Retinal Screening Report',16,y);y+=9;doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text('Bilateral fundus AI + verified systemic context + entered ophthalmic examination findings',16,y);y+=10;
  line('Patient',p.name);line('Generated',fmt(r.generatedAt));if(s.clinicalContext?.reportAnalysis)line('Diabetes report extraction',`${s.clinicalContext.reportAnalysis.method} · ${s.clinicalContext.reportAnalysis.overallConfidence}% extraction confidence · ${s.clinicalContext.verifiedByPHC?'PHC reviewed':'not marked PHC-reviewed'}`);line('Overall AI grade',`Level ${r.overallSeverity} — ${r.overallLabel}`);line('Referable',r.referable?'Yes':'No');line('Model confidence',`${Math.round(r.confidence*100)}% (confidence is not accuracy)`);line('Right fundus AI',`${r.rightLabel}; quality ${s.right.quality} ${s.right.qualityScore??'—'}/100`);line('Left fundus AI',`${r.leftLabel}; quality ${s.left.quality} ${s.left.qualityScore??'—'}/100`);
  heading('Ophthalmology / Retinal Clinical Findings');
  const rows=r.clinicalFindings||buildClinicalFindingRows(s);
  rows.forEach(row=>{ensure(22);doc.setFont('helvetica','bold');doc.text(row.examination,16,y);y+=5;doc.setFont('helvetica','normal');const rr=doc.splitTextToSize(`Right: ${row.right}`,178);doc.text(rr,20,y);y+=rr.length*4.5;const ll=doc.splitTextToSize(`Left: ${row.left}`,178);doc.text(ll,20,y);y+=ll.length*4.5;doc.setTextColor(105,120,125);doc.text(`Source: ${row.source}`,20,y);doc.setTextColor(0,0,0);y+=7});
  heading('Systemic Diabetes Context');line('Context',r.systemicContext.join(' | ')||'Not available');
  heading('Retinal AI Summary');line('AI findings',r.retinalSummary.join(' | ')||'Not available');
  heading('Clinical Coordination');line('Recommendation',r.recommendation);line('Follow-up',r.followUp);line('Model',`${ai.model?.name||'trained model'} · ${ai.model?.source||''}`);line('Limitations',r.limitation);
  ensure(10);doc.setFontSize(8);doc.setTextColor(90,100,105);doc.text('Decision support only. Tests not performed are not inferred. Final diagnosis and management require qualified ophthalmologist/retina-specialist review.',16,y+4);doc.setTextColor(0,0,0);
  doc.save(`DRISHTI-AI-${String(p.name).replace(/\s+/g,'-')}-Detailed-PHC-Report.pdf`)
}

function AllScreenings({phcId}:{phcId:string}){const d=readDB();const ss=d.screenings.filter(s=>s.phcId===phcId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return <><PageTitle title="Screenings" sub="All PHC retinal capture sessions and AI status."/>{!ss.length?<Empty title="No screenings" body="Completed capture sessions will appear here."/>:<div className="card phc-table-card"><table className="table"><thead><tr><th>Patient</th><th>Date</th><th>R/L quality</th><th>AI grade</th><th>Status</th></tr></thead><tbody>{ss.map(s=><tr key={s.id}><td><b>{d.patients.find(p=>p.id===s.patientId)?.name}</b></td><td>{new Date(s.createdAt).toLocaleDateString()}</td><td>{s.right.quality} / {s.left.quality}</td><td>{s.aiResult?`Level ${s.aiResult.severity} · ${severityNames[s.aiResult.severity]}`:'Not run'}</td><td><Status tone={s.status==='submitted'?'warn':undefined}>{s.status}</Status></td></tr>)}</tbody></table></div>}</>}

function Reports({phcId}:{phcId:string}){const d=readDB();const ss=d.screenings.filter(s=>s.phcId===phcId&&s.phcReport).sort((a,b)=>String(b.phcReport?.generatedAt).localeCompare(String(a.phcReport?.generatedAt)));return <><PageTitle title="AI Reports" sub="Structured bilateral fundus + verified diabetes-context reports."/>{!ss.length?<Empty title="No AI reports yet" body="Generate a detailed report from the fundus screening workspace."/>:<div className="grid grid-2">{ss.map(s=>{const p=d.patients.find(p=>p.id===s.patientId);const r=s.phcReport!;return <div className="card report-list-card" key={s.id}><div className="section-head"><div><span className="eyebrow">{r.overallLabel}</span><h3>{p?.name}</h3></div><Status tone={r.priority==='urgent'?'bad':r.priority==='priority'?'warn':undefined}>{r.priority}</Status></div><div className="report-list-stats"><span><b>{Math.round(r.confidence*100)}%</b><small>model confidence</small></span><span><b>{r.referable?'Yes':'No'}</b><small>referable</small></span><span><b>{s.status}</b><small>review state</small></span></div><p className="muted">{r.recommendation}</p><button className="btn ghost" onClick={()=>downloadPHCReport(s,p)}><FileDown size={16}/>Download detailed PDF</button></div>})}</div>}</>}

function Referrals({phcId}:{phcId:string}){const d=readDB();const ids=new Set(d.screenings.filter(s=>s.phcId===phcId).map(s=>s.id));const rs=d.referrals.filter(r=>ids.has(r.screeningId));const update=(r:any,status:'recommended'|'scheduled'|'completed')=>saveReferral({...r,status});return <><PageTitle title="Referrals" sub="Coordinate ophthalmologist-created referrals without changing the clinical assessment."/>{!rs.length?<Empty title="No referrals" body="Doctor-created referrals for this PHC will appear here."/>:<div className="grid grid-2">{rs.map(r=><div className="card" key={r.id}><Status>{r.status}</Status><h3>{d.patients.find(p=>p.id===r.patientId)?.name}</h3><p>{r.reason}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn ghost" onClick={()=>update(r,'scheduled')}>Mark scheduled</button><button className="btn soft" onClick={()=>update(r,'completed')}>Mark completed</button></div></div>)}</div>}</>}

function PHCConsultations({phcId}:{phcId:string}){const d=readDB();const screens=d.screenings.filter(s=>s.phcId===phcId);const patientIds=new Set(screens.map(s=>s.patientId));const list=d.consultations.filter(c=>c.phcId===phcId||patientIds.has(c.patientId));const[patientId,setPatientId]=useState(d.appointments.find(a=>a.phcId===phcId)?.patientId||'');const[when,setWhen]=useState('');const[reason,setReason]=useState('Remote retina specialist review requested by PHC');function create(){if(!patientId||!when)return alert('Choose patient and schedule.');saveConsultation({id:uid('call'),patientId,phcId,scheduledAt:new Date(when).toISOString(),status:'scheduled',reason,roomId:`drishti-${uid('room')}`});}return <><PageTitle title="Video consultations" sub="Schedule remote specialist review when travel to a retina specialist is difficult."/><div className="grid grid-2"><div className="card"><h3>Schedule consultation</h3><div className="field"><label>Patient</label><select className="select" value={patientId} onChange={e=>setPatientId(e.target.value)}><option value="">Select patient</option>{d.patients.filter(p=>d.appointments.some(a=>a.phcId===phcId&&a.patientId===p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Date & time</label><input className="input" type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></div><div className="field"><label>Reason</label><textarea className="textarea" value={reason} onChange={e=>setReason(e.target.value)}/></div><button className="btn primary" onClick={create}><Video size={16}/>Schedule secure-room adapter</button></div><div className="card"><h3>Scheduled rooms</h3>{list.length?list.map(c=><div className="consult-row" key={c.id}><Video size={18}/><div><b>{d.patients.find(p=>p.id===c.patientId)?.name||'Patient'}</b><p>{new Date(c.scheduledAt).toLocaleString()} · {c.status}</p></div>{c.status==='scheduled'&&<a className="btn soft" target="_blank" rel="noreferrer" href={`https://meet.jit.si/${c.roomId}`}>Join</a>}</div>):<p className="muted">No video consultations yet.</p>}<div className="disclaimer">Jitsi is a replaceable prototype video-room adapter. Production healthcare use should connect an approved privacy/compliance solution.</div></div></div></>}
