import {motion} from 'framer-motion';
import {ArrowRight,BrainCircuit,Building2,Camera,CheckCircle2,Eye,FileCheck2,HeartPulse,ShieldCheck,Stethoscope,Video} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Footer,PublicNav} from '../components/Common';

const roleCards=[
 {title:'Patient',desc:'Create your health profile, complete risk questions, prepare for retinal screening and book a PHC visit.',icon:HeartPulse,to:'/register',cta:'Start as Patient'},
 {title:'PHC Center',desc:'Register a centre, receive bookings, capture/import fundus images, run quality gates and create screening reports.',icon:Building2,to:'/register-phc',cta:'PHC Workspace'},
 {title:'Retina Specialist',desc:'Review fundus screening evidence, confirm or modify AI recommendations, create care plans and follow-up.',icon:Stethoscope,to:'/register-doctor',cta:'Specialist Workspace'}
];
export function Home(){return <div className="public-page"><PublicNav/>
<section className="container hero hero-new"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><span className="eyebrow">Explainable diabetic retinopathy screening</span><h1>Screen earlier. Route smarter. Keep the retina specialist in control.</h1><p>DRISHTI‑AI connects patient context, guided capture, live PHC discovery, fundus quality checks, trained-model screening support and ophthalmologist review in one rural-first care pathway.</p><div className="hero-ctas"><Link to="/login" className="btn primary">Login <ArrowRight size={17}/></Link><Link to="/register" className="btn soft">Start Screening</Link><Link to="/demo" className="btn ghost">Watch Demo</Link></div><div className="trust"><span><ShieldCheck size={14}/> Human final assessment</span><span><Camera size={14}/> Fundus-camera workflow</span><span><Video size={14}/> Remote specialist handoff</span></div></motion.div>
<motion.div className="retina-shell" initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{duration:.8}}><div className="retina"><div className="scan"/><div className="retina-pulse"/></div><motion.div className="float-card fc1" animate={{y:[0,-8,0]}} transition={{repeat:Infinity,duration:4}}><span className="dot"/>Quality before inference<br/><b>Gradable → Analyze → Review</b></motion.div><motion.div className="float-card fc2" animate={{y:[0,8,0]}} transition={{repeat:Infinity,duration:4.8}}><b>Patient → PHC → Specialist</b><br/><span className="small">One connected screening record</span></motion.div></motion.div></section>
<section className="container solution-rail"><div><span>01</span><b>Health context</b><small>Simple risk questions</small></div><i/><div><span>02</span><b>Guided capture</b><small>Eye positioning + fundus intake</small></div><i/><div><span>03</span><b>Quality + AI</b><small>Reject poor retinal inputs</small></div><i/><div><span>04</span><b>Clinical review</b><small>Final specialist decision</small></div></section>
<section className="container role-zone"><div className="section-heading"><span className="eyebrow">Choose your workspace</span><h2>One platform. Three clear roles.</h2><p>The same patient record moves through the care pathway instead of being recreated at every step.</p></div><div className="role-grid">{roleCards.map((r,i)=>{const I=r.icon;return <motion.div className="role-card" key={r.title} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}}><div className="role-icon"><I size={26}/></div><h3>{r.title}</h3><p>{r.desc}</p><Link to={r.to} className="role-link">{r.cta}<ArrowRight size={16}/></Link></motion.div>})}</div></section><Footer/></div>}
function PublicInfo({title,lead,items}:{title:string;lead:string;items:[string,string,any][]}){return <div><PublicNav/><section className="container section"><span className="eyebrow">DRISHTI‑AI</span><h2>{title}</h2><p className="lead">{lead}</p><div className="feature-grid">{items.map(([a,b,I])=><motion.div className="feature" key={a} initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><I size={24} color="#176B68"/><h3>{a}</h3><p>{b}</p></motion.div>)}</div></section><Footer/></div>}
export const HowItWorks=()=> <PublicInfo title="A clinically safer screening pathway." lead="Questionnaire context helps prioritize screening; diabetic retinopathy classification itself requires retinal/fundus imaging—not an ordinary selfie of the eye." items={[["1. Patient preparation","Health history and known DR risk factors create a screening-urgency signal. It is not a diagnostic probability.",FileCheck2],["2. Fundus acquisition","PHC or compatible fundus-camera workflows provide right/left retinal images. Ungradable images stop before AI.",Camera],["3. AI + specialist review","A trained DR model supplies screening support and explainability; a retina specialist makes the final clinical assessment.",Stethoscope]]}/>;
export const Patients=()=> <PublicInfo title="Prepare, screen and follow up with less confusion." lead="Patients can create an account, complete a guided health history, upload existing reports, locate registered PHCs, book screening and receive reviewed results." items={[["Health context","Simple questions cover diabetes duration, HbA1c/BP when known, prior eye exams and retinal history.",HeartPulse],["Capture guidance","A camera workflow can assist eye positioning, but retinal disease analysis is only enabled for fundus images.",Eye],["Next action","Results prioritize the safest next step: routine screening, PHC screening or prompt specialist review.",CheckCircle2]]}/>;
export const Providers=()=> <PublicInfo title="PHC screening and specialist review in one record." lead="The provider workflow supports fundus-image import, image-quality gating, trained-model inference, structured observations, referral and tele-ophthalmology." items={[["Interoperable intake","Designed for JPEG/PNG and DICOM/file-based camera adapters; device-specific USB/Wi‑Fi integrations can plug in later.",Camera],["Explainable screening","Model severity, confidence and Grad-CAM can be reviewed alongside clinical observations.",BrainCircuit],["Remote specialist","PHCs can request a retina specialist review and schedule a video consultation for patients who are far away.",Video]]}/>;
export const About=()=> <PublicInfo title="Designed to avoid fake certainty." lead="DRISHTI‑AI is a decision-support workflow. It does not label research-model output as guaranteed diagnosis, and it never invents lesion findings that a model or clinician did not actually provide." items={[["Quality gate","Ungradable fundus images are rejected for recapture instead of forcing a prediction.",ShieldCheck],["Human finalization","AI recommendation and ophthalmologist final assessment remain visibly separate.",Stethoscope],["Replaceable services","Camera, quality, AI, storage, auth and telemedicine layers are modular integration points.",CheckCircle2]]}/>;
