import {Activity,BrainCircuit,ChevronRight,FileText,HeartPulse,LogOut,ShieldCheck,UserRound} from 'lucide-react';
import {NavLink,Link} from 'react-router-dom';
import {useAuth} from '../contexts/AuthContext';
export function Brand(){return <Link to="/" className="brand"><span className="brandmark"><Activity size={20}/></span><span>DRISHTI‑AI</span></Link>}
export function PublicNav(){return <header className="container nav"><Brand/><nav className="navlinks"><NavLink to="/">Home</NavLink><NavLink to="/how-it-works">How It Works</NavLink><NavLink to="/patients">For Patients</NavLink><NavLink to="/providers">For Healthcare Providers</NavLink><NavLink to="/about">About</NavLink></nav><div className="actions"><Link className="btn ghost" to="/demo">Watch Demo</Link><Link className="btn ghost" to="/login">Login</Link><Link className="btn primary" to="/register">Get Started</Link></div></header>}
export function Footer(){return <footer className="footer"><div className="container" style={{display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'}}><Brand/><span>AI screening support ≠ medical diagnosis. Final clinical assessment belongs to a qualified ophthalmologist.</span></div></footer>}
const icons:any={dashboard:HeartPulse,profile:UserRound,reports:FileText,ai:BrainCircuit,security:ShieldCheck};
export function PortalLayout({role,links,children}:{role:string;links:{to:string,label:string,icon?:string}[];children:React.ReactNode}){const {logout,user}=useAuth();return <div className="app-shell"><aside className="sidebar"><Brand/><div className="small" style={{margin:'12px 10px 0'}}>{role} workspace</div><nav className="side-nav">{links.map(l=>{const I=icons[l.icon||'dashboard']||ChevronRight;return <NavLink key={l.to} to={l.to} className={({isActive})=>'side-link '+(isActive?'active':'')}><I size={17}/>{l.label}</NavLink>})}</nav><div className="side-bottom"><div className="card" style={{padding:13,marginBottom:10}}><strong style={{fontSize:13}}>{user?.name}</strong><div className="small">{user?.email}</div></div><button className="btn ghost" style={{width:'100%'}} onClick={logout}><LogOut size={16}/>Logout</button></div></aside><main className="main">{children}</main><nav className="mobilebar">{links.slice(0,5).map(l=><NavLink key={l.to} to={l.to}><ChevronRight size={20}/></NavLink>)}</nav></div>}
export function PageTitle({title,sub,action}:{title:string;sub?:string;action?:React.ReactNode}){return <div className="topbar"><div className="page-title"><h1>{title}</h1>{sub&&<p>{sub}</p>}</div>{action}</div>}
export function Empty({title,body,action}:{title:string;body:string;action?:React.ReactNode}){return <div className="empty"><h3 style={{color:'#17242B'}}>{title}</h3><p>{body}</p>{action}</div>}
export function Status({children,tone}:{children:React.ReactNode;tone?:'warn'|'bad'}){return <span className={'badge '+(tone||'')}>{children}</span>}
